# Q1. Pandas version

What version of Pandas did you install?

In [66]:
import pandas as pd
import numpy as np
import matplotlib as mpl
import seaborn as sns

print(f"Pandas version {pd.__version__}")
print(f"NumPy version {np.__version__}")
print(f"Matplotlib version {mpl.__version__}")
print(f"Seaborn version {sns.__version__}")

Pandas version 3.0.5
NumPy version 2.5.3
Matplotlib version 3.11.2
Seaborn version 0.13.2

# Q2. Records count

How many records are in the dataset?

In [67]:
df = pd.read_csv("car_fuel_efficiency_2026.csv")
df.shape

(10000, 11)

In [68]:
df.describe()

,model_year,num_doors,engine_displacement,num_cylinders,horsepower,vehicle_weight,acceleration,fuel_efficiency_mpg
count,10000.000000,10000.00000,10000.000000,10000.000000,9123.000000,10000.000000,9736.000000,10000.000000
mean,1999.549500,3.50400,2268.807000,6.035200,254.446016,4286.754000,18.888044,29.997700
std,14.207925,0.95209,183.447355,0.542578,22.844613,266.212491,1.279543,2.930245
min,1975.000000,2.00000,1590.000000,4.000000,171.000000,3320.000000,14.000000,19.800000
25%,1987.000000,3.00000,2150.000000,6.000000,239.000000,4110.000000,18.000000,28.000000
50%,2000.000000,4.00000,2270.000000,6.000000,254.000000,4280.000000,18.900000,30.000000
75%,2012.000000,4.00000,2390.000000,6.000000,270.000000,4470.000000,19.700000,31.900000
max,2024.000000,5.00000,3110.000000,8.000000,334.000000,5460.000000,23.800000,41.200000

In [69]:
df.head()

,model_year,origin,fuel_type,drivetrain,num_doors,engine_displacement,num_cylinders,horsepower,vehicle_weight,acceleration,fuel_efficiency_mpg
0,2006,Europe,Gasoline,Front-wheel drive,4,2180,6,243.0,3870,NaN,31.9
1,2008,Europe,Diesel,Front-wheel drive,4,2390,6,272.0,4210,NaN,31.3
2,1996,Asia,Gasoline,Front-wheel drive,5,2320,6,267.0,4240,17.3,27.5
3,1989,Europe,Gasoline,Front-wheel drive,4,2130,6,258.0,4490,18.7,28.5
4,1994,USA,Diesel,Front-wheel drive,3,2580,7,304.0,4510,17.5,31.0

# Q3. Fuel types

How many fuel types are presented in the dataset?

In [70]:
df.groupby("fuel_type").model_year.max()

fuel_type
Diesel      2024
Gasoline    2024
Hybrid      2024
Name: model_year, dtype: int64

In [71]:
df.fuel_type.nunique()

3

In [72]:
df.nunique()

model_year              50
origin                   3
fuel_type                3
drivetrain               3
num_doors                4
engine_displacement    127
num_cylinders            5
horsepower             153
vehicle_weight         176
acceleration            93
fuel_efficiency_mpg    188
dtype: int64

# Q4. Missing values

How many columns in the dataset have missing values?

In [73]:
df.isnull().sum()

model_year               0
origin                   0
fuel_type                0
drivetrain               0
num_doors                0
engine_displacement      0
num_cylinders            0
horsepower             877
vehicle_weight           0
acceleration           264
fuel_efficiency_mpg      0
dtype: int64

# Q5. Max fuel efficiency

What's the maximum fuel efficiency of cars from Asia?

In [74]:
df.groupby("origin").fuel_efficiency_mpg.max()

origin
Asia      41.2
Europe    39.4
USA       38.2
Name: fuel_efficiency_mpg, dtype: float64

In [75]:
df[df["origin"] == "Asia"]["fuel_efficiency_mpg"].max()

np.float64(41.2)

# Q6. Median value of horsepower

1. Find the median value of the horsepower column in the dataset.
2. Next, calculate the most frequent value of the same horsepower column.
3. Use the fillna method to fill the missing values in the horsepower column with the most frequent value from the previous step.
4. Now, calculate the median value of horsepower once again.
Has it changed? (Yes, it increased / Yes, it decreased / No)

In [76]:
original_median_horsepower = df.horsepower.median()
original_median_horsepower

np.float64(254.0)

In [81]:
(df["horsepower"] == original_median_horsepower).sum()

np.int64(155)

In [63]:
most_common_horsepower = df.horsepower.mode()[0]
most_common_horsepower

np.float64(252.0)

In [78]:
df.horsepower.isnull().sum()

np.int64(877)

In [64]:
df.horsepower = df.horsepower.fillna(most_common_horsepower)

In [65]:
new_median_horsepower = df.horsepower.median()
new_median_horsepower

np.float64(252.0)

# Q7. Sum of weights

1. Select all the cars from Asia
2. Select only columns vehicle_weight and model_year
3. Select the first 7 values
4. Get the underlying NumPy array. Let's call it X.
5. Compute matrix-matrix multiplication between the transpose of X and X. To get the transpose, use X.T. Let's call the result XTX.
6. Invert XTX.
7. Create an array y with values [1100, 1300, 800, 900, 1000, 1100, 1200].
8. Multiply the inverse of XTX with the transpose of X, and then multiply the result by y. Call the result w.
9. What's the sum of all the elements of the result?

In [101]:
X = df[df["origin"] == "Asia"][["vehicle_weight", "model_year"]].head(7)
X

    vehicle_weight  model_year
2             4240        1996
6             4310        1992
8             4230        1997
10            4420        1978
15            3950        2007
16            4750        2021
22            4450        2019

In [102]:
XTX = X.T.dot(X) # or X.T @ X
XTX

                vehicle_weight  model_year
vehicle_weight       131950500    60750580
model_year            60750580    28041424

In [103]:
XTX_inv = np.linalg.inv(XTX)
XTX_inv

array([[ 2.96830537e-06, -6.43071025e-06],
       [-6.43071025e-06,  1.39675281e-05]])

In [104]:
y = np.array([1100, 1300, 800, 900, 1000, 1100, 1200])
y

array([1100, 1300,  800,  900, 1000, 1100, 1200])

In [106]:
z = XTX_inv @ X.T
z

         2         6         8         10        15        16        22
0 -0.000250 -0.000017 -0.000286  0.000400 -0.001182  0.001103  0.000225
1  0.000613  0.000107  0.000691 -0.000796  0.002632 -0.002317 -0.000416

In [110]:
w = z @ y
w

0    0.136448
1    0.232749
dtype: float64

In [112]:
w.sum()

np.float64(0.369196969049255)